libutee: arm32: make __utee_entry() an assembler wrapper
Clang does not accept the .cantunwind directive in the C function
__utee_entry():

 lib/libutee/arch/arm/user_ta_entry.c:208:6: error: .fnstart must precede .cantunwind directive
         asm(".cantunwind");
             ^
 <inline asm>:1:2: note: instantiated into assembly here
         .cantunwind
         ^

Therefore, write an assembler wrapper instead.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>